### ISSUE TITLE
Welcome to データミックスゼミ (2019/07~)

### ISSUE THREAD

**Issue by slaypni** [datamix-datascience/datamix-seminar#1]
データミックスゼミ初回は以下の文献を読んでいきます！
ディスカッションボード\(このレポジトリのIssues\)を活用して、参加者同士で理解を深めていきましょう！

[キックオフ スライド](https://www.slideshare.net/secret/uClepfVwVyYQxq)

## NLP

- 深層学習による自然言語処理 \[[Amazon](https://www.amazon.co.jp/%E6%B7%B1%E5%B1%A4%E5%AD%A6%E7%BF%92%E3%81%AB%E3%82%88%E3%82%8B%E8%87%AA%E7%84%B6%E8%A8%80%E8%AA%9E%E5%87%A6%E7%90%86-%E6%A9%9F%E6%A2%B0%E5%AD%A6%E7%BF%92%E3%83%97%E3%83%AD%E3%83%95%E3%82%A7%E3%83%83%E3%82%B7%E3%83%A7%E3%83%8A%E3%83%AB%E3%82%B7%E3%83%AA%E3%83%BC%E3%82%BA-%E5%9D%AA%E4%BA%95-%E7%A5%90%E5%A4%AA/dp/4061529242/)\]
  - 1.1 ~ 4.1

## 推薦システム

- Matrix factorization techniques for recommender systems \[[pdf](https://datajobs.com/data-science-repo/Recommender-Systems-[Netflix].pdf)\]

**Comment by kentayamashita** [comment]
山下です。
NLPの赤本ですが、以前こちらのグループで輪読会が行われており（今年前半）、
章によっては企業の方や学生の方が作った説明パワポを上げてくださっていますので
ご参考までに共有します。
https://nlpaper-challenge.connpass.com/

**Comment by slaypni** [comment]
https://spinningup.openai.com/en/latest/spinningup/rl_intro3.html#baselines-in-policy-gradients
